import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Institutional Intelligence design system
        "error": "#ffb4ab",
        "surface-dim": "#10131a",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#8292aa",
        "on-background": "#e1e2ec",
        "secondary-fixed": "#62fae3",
        "surface-variant": "#32353c",
        "inverse-primary": "#005ac2",
        "on-primary-fixed": "#001a42",
        "surface-container-high": "#272a31",
        "background": "#10131a",
        "inverse-on-surface": "#2e3038",
        "surface-container-low": "#191b23",
        "on-tertiary-fixed-variant": "#38485d",
        "tertiary": "#b7c8e1",
        "on-surface-variant": "#c2c6d6",
        "primary": "#adc6ff",
        "on-secondary-fixed-variant": "#005047",
        "on-primary-container": "#00285d",
        "on-secondary": "#003731",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-tertiary-container": "#1a2b3e",
        "on-secondary-fixed": "#00201c",
        "on-primary-fixed-variant": "#004395",
        "secondary": "#44e2cd",
        "surface-tint": "#adc6ff",
        "surface-bright": "#363941",
        "surface-container-lowest": "#0b0e15",
        "surface-container": "#1d2027",
        "on-tertiary-fixed": "#0b1c30",
        "surface": "#10131a",
        "primary-container": "#4d8eff",
        "outline-variant": "#424754",
        "error-container": "#93000a",
        "on-tertiary": "#213145",
        "on-secondary-container": "#004d44",
        "primary-fixed-dim": "#adc6ff",
        "on-surface": "#e1e2ec",
        "secondary-fixed-dim": "#3cddc7",
        "secondary-container": "#03c6b2",
        "tertiary-fixed": "#d3e4fe",
        "surface-container-highest": "#32353c",
        "on-primary": "#002e6a",
        "outline": "#8c909f",
        "inverse-surface": "#e1e2ec",
        "tertiary-fixed-dim": "#b7c8e1",
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "body-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "label-sm": ["Manrope"],
        "data-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "unit": "4px",
        "gutter": "16px",
        "margin-desktop": "32px",
        "container-max": "1440px",
      },
      animation: {
        shiny: 'shiny 6s linear infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        shiny: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
      },
    },
  },
  plugins: [
    typography,
  ],
}
